### ISSUE TITLE
Switch environment variables to `.env`, and make `direnv` optional

### ISSUE THREAD

**Issue by avisionh** [best-practice-and-impact/govcookiecutter#28]
I haven't tested this out myself so unsure if it will work but it sounds like you can replace the line in the `.envrc` file [here](https://github.com/ukgovdatascience/govcookiecutter/blob/main/%7B%7B%20cookiecutter.repo_name%20%7D%7D/.envrc#L18) with `dotenv`.

https://github.com/direnv/direnv/issues/284#issuecomment-315275436

Adds an extra dependency but you'll need this dependency anyways if you want to use the `.envrc` framework within PyCharm.

**Comment by ESKYoung** [comment]
Interesting! Reading the [documentation](https://direnv.net/man/direnv-stdlib.1.html#codedotenv-ltdotenvpathgtcode), calling `dotenv .env` (for example) in `.envrc` will load the `.env` file. So it seems it won't do the reverse (parse the `.envrc` file, into a `.env` file), which is what the [`sed` command](https://github.com/ukgovdatascience/govcookiecutter/blob/main/%7B%7B%20cookiecutter.repo_name%20%7D%7D/.envrc#L18) does.

However, this is parsing is a bit difficult to do (see the [Windows issue](https://github.com/ukgovdatascience/govcookiecutter/issues/20#issuecomment-827673936)), and definitely not scalable (to a certain degree). I wonder instead if we should revise **how** we deal with environment variables.

Maybe we have a `.env` file with all non-secret environment variables, an untracked `.secrets` file in `var=value` format (like `.env`), and then direnv is optional but helps tie it all together? Although optional, you wouldn't (for example) have to load environment variables with `python-dotenv` using direnv. For Windows users (and PyCharm users), you'd have to load both the `.env` and `.secrets` files.

@exfalsoquodlibet - tagging you for reference.

**Opinions welcome**

**Comment by ESKYoung** [comment]
I think I'm going to go ahead and implement the above - this will be a breaking change. Main reasons are that it'll be easier for Windows users, PyCharm users, and any Unix users **without** `direnv` installed to use this repository.

Things to do (in case anyone gets there before I do!):

1. Remove `.gitignore` on `.env`
2. Transfer all environment variables in `.envrc` over to `.env` in `var=value` support
3. Add `dotenv` commands in `direnv` to point to `.env` and `.secrets`
    - Maybe using [`dotenv_if_exists`](https://direnv.net/man/direnv-stdlib.1.html#codedotenvifexists-ltdotenvpathgtcode) for `.secrets` or add a `touch .secrets` command to `direnv`
4. Revise the documentation in `.envrc` and `.secrets`
5. Update/modify the tests in `tests/test_envrc.py` including renaming the file
6. Consider adding [`python-dotenv`](https://github.com/theskumar/python-dotenv) to `requirements.txt`

**Comment by ESKYoung** [comment]
[Made an initial start on this in the `make-direnv-optional` branch](https://github.com/ukgovdatascience/govcookiecutter/tree/make-direnv-optional), which covers Points 1-3, and 5-6; this branches off [`revise-documentation`, which is currently in review](https://github.com/ukgovdatascience/govcookiecutter/pull/33).

**Comment by ESKYoung** [comment]
Rebased the above branch up to version 1.2.0, but don't have time to finish this! Any help would be much appreciated.

**Comment by AndreasThinks** [comment]
So what needs doing on this?  I'm a bit lost :P

**Comment by ESKYoung** [comment]
@AndreasThinks I think all this needs are changes to the documentation, i.e.:

- modifying any and all mentions of environment variables to refer to the `VARIABLE=VALUE` format
- similarly stating those variables should go in the `.env` file
- new documentation to state this can be loaded with the `python-dotenv` package
- revision of the documentation to state that using `python-dotenv` isn't necessary for Unix-based users with `direnv` installed, since that will load `.env` using `.envrc`

Might be some other bits, but should all be documentation-based.

Fair warning, might need a rebase onto the latest `main` first since the last commit affected documentation quite heavily!

@AndreasThinks - if you're happy to volunteer to write the docs, I can assist with the rebasing if you don't have the right privileges for this repo!

**Comment by AndreasThinks** [comment]
@ESKYoung let me go try and muck in!  So is "best-practice" with the current model for windows users to load the .secret and .env files using their relative path?

I haven't done much contributing to projects on Github before and not read the contributing docs in detail... so not quite sure about how rebasing works...I was just going to do a fork with the some new docs and submit a pull request later!

**Comment by ESKYoung** [comment]
@AndreasThinks - with the changes I've suggest, yes it'll be loading it in. Relative path will be more maintainable, especially if there are collaborators in the project.

I believe @Jacobb164 has made some changes to the branch now, that may cover most (if not all) the remaining tasks! Will leave it in their capable hands! 😄

**Comment by Jacobb164** [comment]
Completed and merged
