### ISSUE TITLE
Python 3.10 - DLL load fail

### ISSUE THREAD

**Issue by HarrisonJeffrey** [best-practice-and-impact/govcookiecutter#52]
Hi all,

Just as a heads up - there seems to be an issue with Python 3.10 and running the .pre-commit-config during the initial commit. When it begins installing the environments for each library in the config yaml, the following gets thrown back:

> ImportError: DLL load failed while importing _ctypes: The specified module could not be found.

Downgrading to Python 3.9 fixes this but I thought it may be good to have this recorded in case anyone else bumps into it. Potentially a dependency issue?

I've only tested this on anaconda virtual environments on Windows 10.

**Comment by Jacobb164** [comment]
This will be fixed with the next update which is to be released tomorrow (16/09/2022).
