### ISSUE TITLE
Precommit fails to install isort

### ISSUE THREAD

**Issue by cpiazz** [best-practice-and-impact/govcookiecutter#73]
Precommit fails to install isort hook with the following error

[INFO] Installing environment for https://github.com/pycqa/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/builds/.../.cache/pre-commit/repo0_h0f938/py_env-python3.8/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
[...]
stderr:
      ERROR: Command errored out with exit status 1:
[...]
        File "/tmp/pip-build-env-_3j1398p/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
        File "/tmp/pip-build-env-_3j1398p/overlay/lib/python3.8/site-packages/poetry/core/factory.py", line 57, in create_poetry
          raise RuntimeError("The Poetry configuration is invalid:\n" + message)
      RuntimeError: The Poetry configuration is invalid:
        - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'

**Comment by cpiazz** [comment]
UPDATE 

I solved this issue by:

- upgrading isort to version 5.12.0
- editing the .pre-commit-config.yaml line 24 as follow: rev: 5.8.0 ---> rev: 5.12.0

Hope this will help!

**Comment by Jacobb164** [comment]
@joshlynchONS can you take a look at this please?

**Comment by joshlynchONS** [comment]
Yeah this has been fixed now @Jacobb164
