### ISSUE TITLE
Missing Python Requirements

### ISSUE THREAD

**Issue by Jday7879** [best-practice-and-impact/govcookiecutter#98]
The created repo does not contain a requirements.txt folder. 
This should include packages needed to install the pre-commit hooks and build documentation?

coverage
detect-secrets==1.0.3
myst-parser
pre-commit
pytest
Sphinx
toml
black
isort
nbstripout
nbqa
pre_commit_hooks
flake8
bandit

**Comment by jamesmyatt** [comment]
See here:  https://github.com/best-practice-and-impact/govcookiecutter/blob/main/%7B%7B%20cookiecutter.repo_name%20%7D%7D/README.md#requirements
